openapi: 3.0.0
info:
  title: MERN Shortner API
  version: 1.0.0
  description: API documentation using Swagger/OpenAPI
paths:
  /url/shorten:
    post:
      tags:
        - URL
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
      responses:
        "201":
          description: Successfully Generated a shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  url:
                    type: object
                    properties:
                      urlId:
                        type: string
                        example: "DbWSWZqjBaS1nCn2WIfB7"
                      longUrl:
                        type: string
                        example: "https://github.com/ai/nanoid#readme"
                      shortUrl:
                        type: string
                        example: "http://localhost:5001/url/DbWSWZqjBaS1nCn2WIfB7"
                      _id:
                        type: string
                        example: "660a9af5fa222802a15a4316"
                      createdAt:
                        type: string
                        format: date-time
                        example: "2024-04-01T11:31:01.430Z"
                      updatedAt:
                        type: string
                        format: date-time
                        example: "2024-04-01T11:31:01.430Z"
                      __v:
                        type: integer
                        example: 0
        "400":
          description: Bad request
          content:
            application/json: {}
  /url/{id}:
    get:
      tags:
        - URL
      summary: Retrieve URL by ID
      description: Retrieve the long URL associated with the given ID
      parameters:
        - in: path
          name: id
          description: ID of the URL to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Redirects to the long URL
          headers:
            Location:
              description: URL to redirect to
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Missing URL Id
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: URL not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Internal Server Error
  /urls:
    get:
      tags:
        - URL
      summary: Retrieve all URLs
      description: Retrieve all URLs stored in the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  urls:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: "660ab8d2c02fcc6b0b3db742"
                        urlId:
                          type: string
                          example: "nyvEm4cZ5sjuIa7-E8szo"
                        longUrl:
                          type: string
                          example: "https://www.longurl.com/longer/longerer/longerest"
                        shortUrl:
                          type: string
                          example: "http://localhost:5001/url/nyvEm4cZ5sjuIa7-E8szo"
                        createdAt:
                          type: string
                          format: date-time
                          example: "2024-04-01T13:38:26.091Z"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Internal Server Error